import type { Admin } from './store';

export const DEMO_VERSION = 'v1_rich_dataset';

export const initialAdmins: Admin[] = [
  {
    "id": "A001",
    "name": "Rajesh Kumar",
    "department": "Water Supply",
    "departmentId": "D101",
    "state": "Maharashtra",
    "district": "Mumbai",
    "status": "Active",
    "assignedGrievances": 3,
    "resolvedGrievances": 0,
    "pendingGrievances": 3,
    "overdueGrievances": 2,
    "averageResolutionHours": 29,
    "slaCompliance": 96
  },
  {
    "id": "A002",
    "name": "Priya Sharma",
    "department": "Electricity",
    "departmentId": "D102",
    "state": "Delhi",
    "district": "New Delhi",
    "status": "Active",
    "assignedGrievances": 3,
    "resolvedGrievances": 0,
    "pendingGrievances": 3,
    "overdueGrievances": 1,
    "averageResolutionHours": 50,
    "slaCompliance": 87
  },
  {
    "id": "A003",
    "name": "Amit Singh",
    "department": "Roads & Infrastructure",
    "departmentId": "D103",
    "state": "Uttar Pradesh",
    "district": "Kanpur",
    "status": "Active",
    "assignedGrievances": 3,
    "resolvedGrievances": 1,
    "pendingGrievances": 2,
    "overdueGrievances": 0,
    "averageResolutionHours": 15,
    "slaCompliance": 71
  },
  {
    "id": "A004",
    "name": "Sneha Gupta",
    "department": "Sanitation",
    "departmentId": "D104",
    "state": "Karnataka",
    "district": "Bengaluru",
    "status": "Active",
    "assignedGrievances": 2,
    "resolvedGrievances": 1,
    "pendingGrievances": 1,
    "overdueGrievances": 0,
    "averageResolutionHours": 40,
    "slaCompliance": 90
  },
  {
    "id": "A005",
    "name": "Arjun Verma",
    "department": "Waste Management",
    "departmentId": "D105",
    "state": "West Bengal",
    "district": "Kolkata",
    "status": "Active",
    "assignedGrievances": 4,
    "resolvedGrievances": 0,
    "pendingGrievances": 4,
    "overdueGrievances": 1,
    "averageResolutionHours": 23,
    "slaCompliance": 73
  },
  {
    "id": "A006",
    "name": "Neha Patel",
    "department": "Public Transport",
    "departmentId": "D106",
    "state": "Gujarat",
    "district": "Ahmedabad",
    "status": "Active",
    "assignedGrievances": 4,
    "resolvedGrievances": 0,
    "pendingGrievances": 4,
    "overdueGrievances": 2,
    "averageResolutionHours": 17,
    "slaCompliance": 77
  },
  {
    "id": "A007",
    "name": "Rohan Mehta",
    "department": "Street Lighting",
    "departmentId": "D107",
    "state": "Rajasthan",
    "district": "Jaipur",
    "status": "Active",
    "assignedGrievances": 4,
    "resolvedGrievances": 2,
    "pendingGrievances": 2,
    "overdueGrievances": 0,
    "averageResolutionHours": 20,
    "slaCompliance": 93
  },
  {
    "id": "A008",
    "name": "Ananya Das",
    "department": "Drainage",
    "departmentId": "D108",
    "state": "Odisha",
    "district": "Bhubaneswar",
    "status": "Active",
    "assignedGrievances": 2,
    "resolvedGrievances": 1,
    "pendingGrievances": 1,
    "overdueGrievances": 0,
    "averageResolutionHours": 19,
    "slaCompliance": 75
  },
  {
    "id": "A009",
    "name": "Vikram Rao",
    "department": "Public Works",
    "departmentId": "D109",
    "state": "Telangana",
    "district": "Hyderabad",
    "status": "Active",
    "assignedGrievances": 3,
    "resolvedGrievances": 1,
    "pendingGrievances": 2,
    "overdueGrievances": 0,
    "averageResolutionHours": 40,
    "slaCompliance": 92
  },
  {
    "id": "A010",
    "name": "Kavya Iyer",
    "department": "Civic Services",
    "departmentId": "D110",
    "state": "Tamil Nadu",
    "district": "Chennai",
    "status": "Active",
    "assignedGrievances": 4,
    "resolvedGrievances": 2,
    "pendingGrievances": 2,
    "overdueGrievances": 0,
    "averageResolutionHours": 12,
    "slaCompliance": 99
  },
  {
    "id": "A011",
    "name": "Manoj Tiwari",
    "department": "Water Supply",
    "departmentId": "D101",
    "state": "Bihar",
    "district": "Patna",
    "status": "Active",
    "assignedGrievances": 2,
    "resolvedGrievances": 1,
    "pendingGrievances": 1,
    "overdueGrievances": 1,
    "averageResolutionHours": 36,
    "slaCompliance": 87
  },
  {
    "id": "A012",
    "name": "Deepa Menon",
    "department": "Electricity",
    "departmentId": "D102",
    "state": "Kerala",
    "district": "Kochi",
    "status": "Active",
    "assignedGrievances": 3,
    "resolvedGrievances": 0,
    "pendingGrievances": 3,
    "overdueGrievances": 1,
    "averageResolutionHours": 53,
    "slaCompliance": 86
  },
  {
    "id": "A013",
    "name": "Sanjay Joshi",
    "department": "Roads & Infrastructure",
    "departmentId": "D103",
    "state": "Madhya Pradesh",
    "district": "Bhopal",
    "status": "Active",
    "assignedGrievances": 4,
    "resolvedGrievances": 1,
    "pendingGrievances": 3,
    "overdueGrievances": 0,
    "averageResolutionHours": 16,
    "slaCompliance": 94
  },
  {
    "id": "A014",
    "name": "Aditi Jain",
    "department": "Sanitation",
    "departmentId": "D104",
    "state": "Maharashtra",
    "district": "Pune",
    "status": "Active",
    "assignedGrievances": 1,
    "resolvedGrievances": 0,
    "pendingGrievances": 1,
    "overdueGrievances": 0,
    "averageResolutionHours": 20,
    "slaCompliance": 88
  },
  {
    "id": "A015",
    "name": "Karan Singh",
    "department": "Waste Management",
    "departmentId": "D105",
    "state": "Uttar Pradesh",
    "district": "Lucknow",
    "status": "Active",
    "assignedGrievances": 4,
    "resolvedGrievances": 3,
    "pendingGrievances": 1,
    "overdueGrievances": 0,
    "averageResolutionHours": 27,
    "slaCompliance": 99
  }
] as any[];

export const initialGrievances: any[] = [
  {
    "id": "GRV-10001",
    "title": "Transformer explosion causing area-wide blackout",
    "citizen": "Ananya Singh",
    "dept": "Electricity",
    "departmentId": "D102",
    "date": "20 Jul 2026",
    "status": "Pending",
    "priority": "Critical",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Transformer explosion causing area-wide blackout. Requires coordination with Electricity department.",
    "location": "Kochi, Kerala",
    "city": "Kochi",
    "district": "Kochi",
    "state": "Kerala",
    "assignedAdminId": "A012",
    "assignedAdminName": "Deepa Menon",
    "createdAt": "2026-07-20T12:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z",
    "dueAt": "2026-08-20T05:04:28.188Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-1-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Ananya Singh",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-20T12:00:00.000Z"
      },
      {
        "id": "ACT-1-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Deepa Menon",
        "timestamp": "2026-07-20T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10002",
    "title": "Bridge collapse hazard on main arterial road",
    "citizen": "Rahul Verma",
    "dept": "Roads & Infrastructure",
    "departmentId": "D103",
    "date": "29 Jul 2026",
    "status": "In Progress",
    "priority": "Critical",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Bridge collapse hazard on main arterial road. Requires coordination with Roads & Infrastructure department.",
    "location": "Kanpur, Uttar Pradesh",
    "city": "Kanpur",
    "district": "Kanpur",
    "state": "Uttar Pradesh",
    "assignedAdminId": "A003",
    "assignedAdminName": "Amit Singh",
    "createdAt": "2026-07-29T12:00:00.000Z",
    "updatedAt": "2026-07-29T12:00:00.000Z",
    "dueAt": "2026-08-19T22:34:51.283Z",
    "escalated": true,
    "escalatedAt": "2026-08-14T02:51:36.131Z",
    "escalatedBy": "System",
    "escalationReason": "SLA severely breached and citizen repeatedly escalated.",
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-2-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Rahul Verma",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-29T12:00:00.000Z"
      },
      {
        "id": "ACT-2-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Amit Singh",
        "timestamp": "2026-07-29T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10003",
    "title": "Severe sewage overflow entering residential homes",
    "citizen": "Priya Das",
    "dept": "Sanitation",
    "departmentId": "D104",
    "date": "07 Aug 2026",
    "status": "Resolved",
    "priority": "Critical",
    "sla": "Resolved",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Severe sewage overflow entering residential homes. Requires coordination with Sanitation department.",
    "location": "Pune, Maharashtra",
    "city": "Pune",
    "district": "Pune",
    "state": "Maharashtra",
    "createdAt": "2026-08-07T12:00:00.000Z",
    "updatedAt": "2026-08-14T15:01:39.286Z",
    "dueAt": "2026-08-08T12:00:00.000Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-3-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Priya Das",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-07T12:00:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10004",
    "title": "Chemical waste dumped near local school",
    "citizen": "Kabir Khan",
    "dept": "Waste Management",
    "departmentId": "D105",
    "date": "26 Jul 2026",
    "status": "In Progress",
    "priority": "Critical",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Chemical waste dumped near local school. Requires coordination with Waste Management department.",
    "location": "Kolkata, West Bengal",
    "city": "Kolkata",
    "district": "Kolkata",
    "state": "West Bengal",
    "assignedAdminId": "A005",
    "assignedAdminName": "Arjun Verma",
    "createdAt": "2026-07-26T12:00:00.000Z",
    "updatedAt": "2026-07-26T12:00:00.000Z",
    "dueAt": "2026-08-15T12:21:46.956Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-4-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Kabir Khan",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-26T12:00:00.000Z"
      },
      {
        "id": "ACT-4-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Arjun Verma",
        "timestamp": "2026-07-26T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10005",
    "title": "Continuous power fluctuation damaging appliances",
    "citizen": "Sneha Iyer",
    "dept": "Electricity",
    "departmentId": "D106",
    "date": "19 Jul 2026",
    "status": "Pending",
    "priority": "Critical",
    "sla": "Overdue",
    "slaColor": "red",
    "aiSummary": "Citizen reported: Continuous power fluctuation damaging appliances. Requires coordination with Electricity department.",
    "location": "Kochi, Kerala",
    "city": "Kochi",
    "district": "Kochi",
    "state": "Kerala",
    "assignedAdminId": "A012",
    "assignedAdminName": "Deepa Menon",
    "createdAt": "2026-07-19T12:00:00.000Z",
    "updatedAt": "2026-07-19T12:00:00.000Z",
    "dueAt": "2026-08-13T22:55:34.564Z",
    "escalated": true,
    "escalatedAt": "2026-08-13T17:35:58.518Z",
    "escalatedBy": "System",
    "escalationReason": "SLA severely breached and citizen repeatedly escalated.",
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-5-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Sneha Iyer",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-19T12:00:00.000Z"
      },
      {
        "id": "ACT-5-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Deepa Menon",
        "timestamp": "2026-07-19T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10006",
    "title": "Deep potholes causing daily accidents",
    "citizen": "Vikram Joshi",
    "dept": "Roads & Infrastructure",
    "departmentId": "D107",
    "date": "19 Jul 2026",
    "status": "Resolved",
    "priority": "Critical",
    "sla": "Resolved",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Deep potholes causing daily accidents. Requires coordination with Roads & Infrastructure department.",
    "location": "Kanpur, Uttar Pradesh",
    "city": "Kanpur",
    "district": "Kanpur",
    "state": "Uttar Pradesh",
    "assignedAdminId": "A003",
    "assignedAdminName": "Amit Singh",
    "createdAt": "2026-07-19T12:00:00.000Z",
    "updatedAt": "2026-08-15T05:28:43.137Z",
    "dueAt": "2026-07-20T12:00:00.000Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-6-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Vikram Joshi",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-19T12:00:00.000Z"
      },
      {
        "id": "ACT-6-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Amit Singh",
        "timestamp": "2026-07-19T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10007",
    "title": "No water supply for 4 consecutive days",
    "citizen": "Pooja Reddy",
    "dept": "Water Supply",
    "departmentId": "D108",
    "date": "02 Aug 2026",
    "status": "Pending",
    "priority": "Critical",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: No water supply for 4 consecutive days. Requires coordination with Water Supply department.",
    "location": "Patna, Bihar",
    "city": "Patna",
    "district": "Patna",
    "state": "Bihar",
    "createdAt": "2026-08-02T12:00:00.000Z",
    "updatedAt": "2026-08-02T12:00:00.000Z",
    "dueAt": "2026-08-18T17:08:18.264Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-7-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Pooja Reddy",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-02T12:00:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10008",
    "title": "Garbage not collected for two weeks",
    "citizen": "Rohan Gupta",
    "dept": "Waste Management",
    "departmentId": "D109",
    "date": "16 Jul 2026",
    "status": "In Progress",
    "priority": "Critical",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Garbage not collected for two weeks. Requires coordination with Waste Management department.",
    "location": "Kolkata, West Bengal",
    "city": "Kolkata",
    "district": "Kolkata",
    "state": "West Bengal",
    "assignedAdminId": "A005",
    "assignedAdminName": "Arjun Verma",
    "createdAt": "2026-07-16T12:00:00.000Z",
    "updatedAt": "2026-07-16T12:00:00.000Z",
    "dueAt": "2026-08-15T14:21:04.815Z",
    "escalated": true,
    "escalatedAt": "2026-08-14T09:32:54.134Z",
    "escalatedBy": "System",
    "escalationReason": "SLA severely breached and citizen repeatedly escalated.",
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-8-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Rohan Gupta",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-16T12:00:00.000Z"
      },
      {
        "id": "ACT-8-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Arjun Verma",
        "timestamp": "2026-07-16T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10009",
    "title": "Streetlights on major highway completely dead",
    "citizen": "Neha Menon",
    "dept": "Street Lighting",
    "departmentId": "D110",
    "date": "16 Jul 2026",
    "status": "Resolved",
    "priority": "High",
    "sla": "Resolved",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Streetlights on major highway completely dead. Requires coordination with Street Lighting department.",
    "location": "Jaipur, Rajasthan",
    "city": "Jaipur",
    "district": "Jaipur",
    "state": "Rajasthan",
    "assignedAdminId": "A007",
    "assignedAdminName": "Rohan Mehta",
    "createdAt": "2026-07-16T12:00:00.000Z",
    "updatedAt": "2026-08-14T20:09:09.790Z",
    "dueAt": "2026-07-19T12:00:00.000Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-9-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Neha Menon",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-16T12:00:00.000Z"
      },
      {
        "id": "ACT-9-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Rohan Mehta",
        "timestamp": "2026-07-16T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10010",
    "title": "Public bus route 414 suspended without notice",
    "citizen": "Aarav Sharma",
    "dept": "Public Transport",
    "departmentId": "D101",
    "date": "21 Jul 2026",
    "status": "In Progress",
    "priority": "High",
    "sla": "Overdue",
    "slaColor": "red",
    "aiSummary": "Citizen reported: Public bus route 414 suspended without notice. Requires coordination with Public Transport department.",
    "location": "Ahmedabad, Gujarat",
    "city": "Ahmedabad",
    "district": "Ahmedabad",
    "state": "Gujarat",
    "assignedAdminId": "A006",
    "assignedAdminName": "Neha Patel",
    "createdAt": "2026-07-21T12:00:00.000Z",
    "updatedAt": "2026-07-21T12:00:00.000Z",
    "dueAt": "2026-08-14T12:07:14.810Z",
    "escalated": false,
    "reopened": true,
    "reopenedAt": "2026-08-14T21:25:19.130Z",
    "reopenedBy": "Citizen",
    "reopenReason": "The issue was marked resolved but the problem persists.",
    "messages": [],
    "activities": [
      {
        "id": "ACT-10-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Aarav Sharma",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-21T12:00:00.000Z"
      },
      {
        "id": "ACT-10-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Neha Patel",
        "timestamp": "2026-07-21T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10011",
    "title": "Open manhole on pedestrian walkway",
    "citizen": "Ananya Singh",
    "dept": "Drainage",
    "departmentId": "D102",
    "date": "07 Aug 2026",
    "status": "Pending",
    "priority": "High",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Open manhole on pedestrian walkway. Requires coordination with Drainage department.",
    "location": "Bhubaneswar, Odisha",
    "city": "Bhubaneswar",
    "district": "Bhubaneswar",
    "state": "Odisha",
    "assignedAdminId": "A008",
    "assignedAdminName": "Ananya Das",
    "createdAt": "2026-08-07T12:00:00.000Z",
    "updatedAt": "2026-08-07T12:00:00.000Z",
    "dueAt": "2026-08-20T00:40:57.766Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-11-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Ananya Singh",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-07T12:00:00.000Z"
      },
      {
        "id": "ACT-11-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Ananya Das",
        "timestamp": "2026-08-07T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10012",
    "title": "Public park equipment broken and rusted",
    "citizen": "Rahul Verma",
    "dept": "Public Works",
    "departmentId": "D103",
    "date": "03 Aug 2026",
    "status": "Resolved",
    "priority": "High",
    "sla": "Resolved",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Public park equipment broken and rusted. Requires coordination with Public Works department.",
    "location": "Hyderabad, Telangana",
    "city": "Hyderabad",
    "district": "Hyderabad",
    "state": "Telangana",
    "createdAt": "2026-08-03T12:00:00.000Z",
    "updatedAt": "2026-08-15T09:16:42.693Z",
    "dueAt": "2026-08-06T12:00:00.000Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-12-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Rahul Verma",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-03T12:00:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10013",
    "title": "Tree branches entangling with overhead power lines",
    "citizen": "Priya Das",
    "dept": "Electricity",
    "departmentId": "D104",
    "date": "22 Jul 2026",
    "status": "Pending",
    "priority": "High",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Tree branches entangling with overhead power lines. Requires coordination with Electricity department.",
    "location": "Kochi, Kerala",
    "city": "Kochi",
    "district": "Kochi",
    "state": "Kerala",
    "assignedAdminId": "A012",
    "assignedAdminName": "Deepa Menon",
    "createdAt": "2026-07-22T12:00:00.000Z",
    "updatedAt": "2026-07-22T12:00:00.000Z",
    "dueAt": "2026-08-17T02:46:30.665Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-13-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Priya Das",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-22T12:00:00.000Z"
      },
      {
        "id": "ACT-13-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Deepa Menon",
        "timestamp": "2026-07-22T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10014",
    "title": "Irregular garbage collection schedule",
    "citizen": "Kabir Khan",
    "dept": "Waste Management",
    "departmentId": "D105",
    "date": "18 Jul 2026",
    "status": "In Progress",
    "priority": "High",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Irregular garbage collection schedule. Requires coordination with Waste Management department.",
    "location": "Kolkata, West Bengal",
    "city": "Kolkata",
    "district": "Kolkata",
    "state": "West Bengal",
    "assignedAdminId": "A005",
    "assignedAdminName": "Arjun Verma",
    "createdAt": "2026-07-18T12:00:00.000Z",
    "updatedAt": "2026-07-18T12:00:00.000Z",
    "dueAt": "2026-08-17T17:19:23.493Z",
    "escalated": true,
    "escalatedAt": "2026-08-14T05:32:05.271Z",
    "escalatedBy": "System",
    "escalationReason": "SLA severely breached and citizen repeatedly escalated.",
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-14-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Kabir Khan",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-18T12:00:00.000Z"
      },
      {
        "id": "ACT-14-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Arjun Verma",
        "timestamp": "2026-07-18T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10015",
    "title": "Low water pressure during morning hours",
    "citizen": "Sneha Iyer",
    "dept": "Water Supply",
    "departmentId": "D106",
    "date": "20 Jul 2026",
    "status": "Resolved",
    "priority": "High",
    "sla": "Resolved",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Low water pressure during morning hours. Requires coordination with Water Supply department.",
    "location": "Patna, Bihar",
    "city": "Patna",
    "district": "Patna",
    "state": "Bihar",
    "assignedAdminId": "A011",
    "assignedAdminName": "Manoj Tiwari",
    "createdAt": "2026-07-20T12:00:00.000Z",
    "updatedAt": "2026-08-15T06:42:03.865Z",
    "dueAt": "2026-07-23T12:00:00.000Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-15-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Sneha Iyer",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-20T12:00:00.000Z"
      },
      {
        "id": "ACT-15-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Manoj Tiwari",
        "timestamp": "2026-07-20T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10016",
    "title": "Faded zebra crossing markings",
    "citizen": "Vikram Joshi",
    "dept": "Roads & Infrastructure",
    "departmentId": "D107",
    "date": "16 Jul 2026",
    "status": "In Progress",
    "priority": "High",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Faded zebra crossing markings. Requires coordination with Roads & Infrastructure department.",
    "location": "Kanpur, Uttar Pradesh",
    "city": "Kanpur",
    "district": "Kanpur",
    "state": "Uttar Pradesh",
    "assignedAdminId": "A003",
    "assignedAdminName": "Amit Singh",
    "createdAt": "2026-07-16T12:00:00.000Z",
    "updatedAt": "2026-07-16T12:00:00.000Z",
    "dueAt": "2026-08-15T17:24:19.413Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-16-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Vikram Joshi",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-16T12:00:00.000Z"
      },
      {
        "id": "ACT-16-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Amit Singh",
        "timestamp": "2026-07-16T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10017",
    "title": "Stray animal menace near market area",
    "citizen": "Pooja Reddy",
    "dept": "Civic Services",
    "departmentId": "D108",
    "date": "30 Jul 2026",
    "status": "Pending",
    "priority": "High",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Stray animal menace near market area. Requires coordination with Civic Services department.",
    "location": "Chennai, Tamil Nadu",
    "city": "Chennai",
    "district": "Chennai",
    "state": "Tamil Nadu",
    "assignedAdminId": "A010",
    "assignedAdminName": "Kavya Iyer",
    "createdAt": "2026-07-30T12:00:00.000Z",
    "updatedAt": "2026-07-30T12:00:00.000Z",
    "dueAt": "2026-08-16T14:38:12.345Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-17-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Pooja Reddy",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-30T12:00:00.000Z"
      },
      {
        "id": "ACT-17-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Kavya Iyer",
        "timestamp": "2026-07-30T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10018",
    "title": "Mosquito breeding in stagnant park water",
    "citizen": "Rohan Gupta",
    "dept": "Sanitation",
    "departmentId": "D109",
    "date": "06 Aug 2026",
    "status": "Resolved",
    "priority": "High",
    "sla": "Resolved",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Mosquito breeding in stagnant park water. Requires coordination with Sanitation department.",
    "location": "Bengaluru, Karnataka",
    "city": "Bengaluru",
    "district": "Bengaluru",
    "state": "Karnataka",
    "assignedAdminId": "A004",
    "assignedAdminName": "Sneha Gupta",
    "createdAt": "2026-08-06T12:00:00.000Z",
    "updatedAt": "2026-08-15T02:35:40.176Z",
    "dueAt": "2026-08-09T12:00:00.000Z",
    "escalated": true,
    "escalatedAt": "2026-08-13T20:41:34.653Z",
    "escalatedBy": "System",
    "escalationReason": "SLA severely breached and citizen repeatedly escalated.",
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-18-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Rohan Gupta",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-06T12:00:00.000Z"
      },
      {
        "id": "ACT-18-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Sneha Gupta",
        "timestamp": "2026-08-06T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10019",
    "title": "Bus shelter roof leaking during rain",
    "citizen": "Neha Menon",
    "dept": "Public Transport",
    "departmentId": "D110",
    "date": "11 Aug 2026",
    "status": "Pending",
    "priority": "High",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Bus shelter roof leaking during rain. Requires coordination with Public Transport department.",
    "location": "Ahmedabad, Gujarat",
    "city": "Ahmedabad",
    "district": "Ahmedabad",
    "state": "Gujarat",
    "assignedAdminId": "A006",
    "assignedAdminName": "Neha Patel",
    "createdAt": "2026-08-11T12:00:00.000Z",
    "updatedAt": "2026-08-11T12:00:00.000Z",
    "dueAt": "2026-08-18T01:13:15.728Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-19-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Neha Menon",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-11T12:00:00.000Z"
      },
      {
        "id": "ACT-19-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Neha Patel",
        "timestamp": "2026-08-11T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10020",
    "title": "Request for additional street dustbins",
    "citizen": "Aarav Sharma",
    "dept": "Waste Management",
    "departmentId": "D101",
    "date": "17 Jul 2026",
    "status": "In Progress",
    "priority": "High",
    "sla": "Overdue",
    "slaColor": "red",
    "aiSummary": "Citizen reported: Request for additional street dustbins. Requires coordination with Waste Management department.",
    "location": "Kolkata, West Bengal",
    "city": "Kolkata",
    "district": "Kolkata",
    "state": "West Bengal",
    "assignedAdminId": "A005",
    "assignedAdminName": "Arjun Verma",
    "createdAt": "2026-07-17T12:00:00.000Z",
    "updatedAt": "2026-07-17T12:00:00.000Z",
    "dueAt": "2026-08-13T18:28:11.734Z",
    "escalated": false,
    "reopened": true,
    "reopenedAt": "2026-08-15T00:32:50.314Z",
    "reopenedBy": "Citizen",
    "reopenReason": "The issue was marked resolved but the problem persists.",
    "messages": [],
    "activities": [
      {
        "id": "ACT-20-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Aarav Sharma",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-17T12:00:00.000Z"
      },
      {
        "id": "ACT-20-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Arjun Verma",
        "timestamp": "2026-07-17T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10021",
    "title": "Streetlight flickering occasionally",
    "citizen": "Ananya Singh",
    "dept": "Street Lighting",
    "departmentId": "D102",
    "date": "11 Aug 2026",
    "status": "Resolved",
    "priority": "Medium",
    "sla": "Resolved",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Streetlight flickering occasionally. Requires coordination with Street Lighting department.",
    "location": "Jaipur, Rajasthan",
    "city": "Jaipur",
    "district": "Jaipur",
    "state": "Rajasthan",
    "assignedAdminId": "A007",
    "assignedAdminName": "Rohan Mehta",
    "createdAt": "2026-08-11T12:00:00.000Z",
    "updatedAt": "2026-08-14T14:16:37.653Z",
    "dueAt": "2026-08-18T12:00:00.000Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-21-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Ananya Singh",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-11T12:00:00.000Z"
      },
      {
        "id": "ACT-21-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Rohan Mehta",
        "timestamp": "2026-08-11T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10022",
    "title": "Minor crack on pavement",
    "citizen": "Rahul Verma",
    "dept": "Roads & Infrastructure",
    "departmentId": "D103",
    "date": "11 Aug 2026",
    "status": "In Progress",
    "priority": "Medium",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Minor crack on pavement. Requires coordination with Roads & Infrastructure department.",
    "location": "Kanpur, Uttar Pradesh",
    "city": "Kanpur",
    "district": "Kanpur",
    "state": "Uttar Pradesh",
    "createdAt": "2026-08-11T12:00:00.000Z",
    "updatedAt": "2026-08-11T12:00:00.000Z",
    "dueAt": "2026-08-19T04:19:23.692Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-22-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Rahul Verma",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-11T12:00:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10023",
    "title": "Delay in processing property tax receipt",
    "citizen": "Priya Das",
    "dept": "Civic Services",
    "departmentId": "D104",
    "date": "30 Jul 2026",
    "status": "Pending",
    "priority": "Medium",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Delay in processing property tax receipt. Requires coordination with Civic Services department.",
    "location": "Chennai, Tamil Nadu",
    "city": "Chennai",
    "district": "Chennai",
    "state": "Tamil Nadu",
    "assignedAdminId": "A010",
    "assignedAdminName": "Kavya Iyer",
    "createdAt": "2026-07-30T12:00:00.000Z",
    "updatedAt": "2026-07-30T12:00:00.000Z",
    "dueAt": "2026-08-19T19:08:56.669Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-23-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Priya Das",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-30T12:00:00.000Z"
      },
      {
        "id": "ACT-23-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Kavya Iyer",
        "timestamp": "2026-07-30T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10024",
    "title": "Park bench requires repainting",
    "citizen": "Kabir Khan",
    "dept": "Public Works",
    "departmentId": "D105",
    "date": "09 Aug 2026",
    "status": "Resolved",
    "priority": "Medium",
    "sla": "Resolved",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Park bench requires repainting. Requires coordination with Public Works department.",
    "location": "Hyderabad, Telangana",
    "city": "Hyderabad",
    "district": "Hyderabad",
    "state": "Telangana",
    "assignedAdminId": "A009",
    "assignedAdminName": "Vikram Rao",
    "createdAt": "2026-08-09T12:00:00.000Z",
    "updatedAt": "2026-08-14T12:59:20.429Z",
    "dueAt": "2026-08-16T12:00:00.000Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-24-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Kabir Khan",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-09T12:00:00.000Z"
      },
      {
        "id": "ACT-24-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Vikram Rao",
        "timestamp": "2026-08-09T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10025",
    "title": "Major water pipeline burst flooding street",
    "citizen": "Sneha Iyer",
    "dept": "Water Supply",
    "departmentId": "D106",
    "date": "06 Aug 2026",
    "status": "Pending",
    "priority": "Medium",
    "sla": "Overdue",
    "slaColor": "red",
    "aiSummary": "Citizen reported: Major water pipeline burst flooding street. Requires coordination with Water Supply department.",
    "location": "Patna, Bihar",
    "city": "Patna",
    "district": "Patna",
    "state": "Bihar",
    "assignedAdminId": "A011",
    "assignedAdminName": "Manoj Tiwari",
    "createdAt": "2026-08-06T12:00:00.000Z",
    "updatedAt": "2026-08-06T12:00:00.000Z",
    "dueAt": "2026-08-14T13:28:49.676Z",
    "escalated": true,
    "escalatedAt": "2026-08-13T13:26:58.453Z",
    "escalatedBy": "System",
    "escalationReason": "SLA severely breached and citizen repeatedly escalated.",
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-25-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Sneha Iyer",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-06T12:00:00.000Z"
      },
      {
        "id": "ACT-25-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Manoj Tiwari",
        "timestamp": "2026-08-06T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10026",
    "title": "Transformer explosion causing area-wide blackout",
    "citizen": "Vikram Joshi",
    "dept": "Electricity",
    "departmentId": "D107",
    "date": "12 Aug 2026",
    "status": "In Progress",
    "priority": "Medium",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Transformer explosion causing area-wide blackout. Requires coordination with Electricity department.",
    "location": "New Delhi, Delhi",
    "city": "New Delhi",
    "district": "New Delhi",
    "state": "Delhi",
    "assignedAdminId": "A002",
    "assignedAdminName": "Priya Sharma",
    "createdAt": "2026-08-12T12:00:00.000Z",
    "updatedAt": "2026-08-12T12:00:00.000Z",
    "dueAt": "2026-08-18T20:23:47.039Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-26-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Vikram Joshi",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-12T12:00:00.000Z"
      },
      {
        "id": "ACT-26-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Priya Sharma",
        "timestamp": "2026-08-12T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10027",
    "title": "Bridge collapse hazard on main arterial road",
    "citizen": "Pooja Reddy",
    "dept": "Roads & Infrastructure",
    "departmentId": "D108",
    "date": "02 Aug 2026",
    "status": "Resolved",
    "priority": "Medium",
    "sla": "Resolved",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Bridge collapse hazard on main arterial road. Requires coordination with Roads & Infrastructure department.",
    "location": "Bhopal, Madhya Pradesh",
    "city": "Bhopal",
    "district": "Bhopal",
    "state": "Madhya Pradesh",
    "assignedAdminId": "A013",
    "assignedAdminName": "Sanjay Joshi",
    "createdAt": "2026-08-02T12:00:00.000Z",
    "updatedAt": "2026-08-14T18:29:27.208Z",
    "dueAt": "2026-08-09T12:00:00.000Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-27-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Pooja Reddy",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-02T12:00:00.000Z"
      },
      {
        "id": "ACT-27-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Sanjay Joshi",
        "timestamp": "2026-08-02T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10028",
    "title": "Severe sewage overflow entering residential homes",
    "citizen": "Rohan Gupta",
    "dept": "Sanitation",
    "departmentId": "D109",
    "date": "11 Aug 2026",
    "status": "In Progress",
    "priority": "Medium",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Severe sewage overflow entering residential homes. Requires coordination with Sanitation department.",
    "location": "Bengaluru, Karnataka",
    "city": "Bengaluru",
    "district": "Bengaluru",
    "state": "Karnataka",
    "assignedAdminId": "A004",
    "assignedAdminName": "Sneha Gupta",
    "createdAt": "2026-08-11T12:00:00.000Z",
    "updatedAt": "2026-08-11T12:00:00.000Z",
    "dueAt": "2026-08-15T22:50:35.185Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-28-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Rohan Gupta",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-11T12:00:00.000Z"
      },
      {
        "id": "ACT-28-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Sneha Gupta",
        "timestamp": "2026-08-11T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10029",
    "title": "Chemical waste dumped near local school",
    "citizen": "Neha Menon",
    "dept": "Waste Management",
    "departmentId": "D110",
    "date": "16 Jul 2026",
    "status": "Pending",
    "priority": "Medium",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Chemical waste dumped near local school. Requires coordination with Waste Management department.",
    "location": "Lucknow, Uttar Pradesh",
    "city": "Lucknow",
    "district": "Lucknow",
    "state": "Uttar Pradesh",
    "assignedAdminId": "A015",
    "assignedAdminName": "Karan Singh",
    "createdAt": "2026-07-16T12:00:00.000Z",
    "updatedAt": "2026-07-16T12:00:00.000Z",
    "dueAt": "2026-08-20T08:31:30.321Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-29-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Neha Menon",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-16T12:00:00.000Z"
      },
      {
        "id": "ACT-29-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Karan Singh",
        "timestamp": "2026-07-16T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10030",
    "title": "Continuous power fluctuation damaging appliances",
    "citizen": "Aarav Sharma",
    "dept": "Electricity",
    "departmentId": "D101",
    "date": "09 Aug 2026",
    "status": "In Progress",
    "priority": "Medium",
    "sla": "Overdue",
    "slaColor": "red",
    "aiSummary": "Citizen reported: Continuous power fluctuation damaging appliances. Requires coordination with Electricity department.",
    "location": "New Delhi, Delhi",
    "city": "New Delhi",
    "district": "New Delhi",
    "state": "Delhi",
    "assignedAdminId": "A002",
    "assignedAdminName": "Priya Sharma",
    "createdAt": "2026-08-09T12:00:00.000Z",
    "updatedAt": "2026-08-15T08:50:16.063Z",
    "dueAt": "2026-08-14T01:33:29.588Z",
    "escalated": false,
    "reopened": true,
    "reopenedAt": "2026-08-14T23:19:06.462Z",
    "reopenedBy": "Citizen",
    "reopenReason": "The issue was marked resolved but the problem persists.",
    "messages": [],
    "activities": [
      {
        "id": "ACT-30-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Aarav Sharma",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-09T12:00:00.000Z"
      },
      {
        "id": "ACT-30-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Priya Sharma",
        "timestamp": "2026-08-09T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10031",
    "title": "Deep potholes causing daily accidents",
    "citizen": "Ananya Singh",
    "dept": "Roads & Infrastructure",
    "departmentId": "D102",
    "date": "19 Jul 2026",
    "status": "Pending",
    "priority": "Medium",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Deep potholes causing daily accidents. Requires coordination with Roads & Infrastructure department.",
    "location": "Bhopal, Madhya Pradesh",
    "city": "Bhopal",
    "district": "Bhopal",
    "state": "Madhya Pradesh",
    "assignedAdminId": "A013",
    "assignedAdminName": "Sanjay Joshi",
    "createdAt": "2026-07-19T12:00:00.000Z",
    "updatedAt": "2026-07-19T12:00:00.000Z",
    "dueAt": "2026-08-19T03:12:16.122Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-31-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Ananya Singh",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-19T12:00:00.000Z"
      },
      {
        "id": "ACT-31-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Sanjay Joshi",
        "timestamp": "2026-07-19T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10032",
    "title": "No water supply for 4 consecutive days",
    "citizen": "Rahul Verma",
    "dept": "Water Supply",
    "departmentId": "D103",
    "date": "26 Jul 2026",
    "status": "In Progress",
    "priority": "Medium",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: No water supply for 4 consecutive days. Requires coordination with Water Supply department.",
    "location": "Mumbai, Maharashtra",
    "city": "Mumbai",
    "district": "Mumbai",
    "state": "Maharashtra",
    "assignedAdminId": "A001",
    "assignedAdminName": "Rajesh Kumar",
    "createdAt": "2026-07-26T12:00:00.000Z",
    "updatedAt": "2026-07-26T12:00:00.000Z",
    "dueAt": "2026-08-15T18:05:21.386Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-32-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Rahul Verma",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-26T12:00:00.000Z"
      },
      {
        "id": "ACT-32-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Rajesh Kumar",
        "timestamp": "2026-07-26T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10033",
    "title": "Garbage not collected for two weeks",
    "citizen": "Priya Das",
    "dept": "Waste Management",
    "departmentId": "D104",
    "date": "13 Aug 2026",
    "status": "Resolved",
    "priority": "Medium",
    "sla": "Resolved",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Garbage not collected for two weeks. Requires coordination with Waste Management department.",
    "location": "Lucknow, Uttar Pradesh",
    "city": "Lucknow",
    "district": "Lucknow",
    "state": "Uttar Pradesh",
    "assignedAdminId": "A015",
    "assignedAdminName": "Karan Singh",
    "createdAt": "2026-08-13T12:00:00.000Z",
    "updatedAt": "2026-08-15T04:03:53.685Z",
    "dueAt": "2026-08-20T12:00:00.000Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-33-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Priya Das",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-13T12:00:00.000Z"
      },
      {
        "id": "ACT-33-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Karan Singh",
        "timestamp": "2026-08-13T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10034",
    "title": "Streetlights on major highway completely dead",
    "citizen": "Kabir Khan",
    "dept": "Street Lighting",
    "departmentId": "D105",
    "date": "31 Jul 2026",
    "status": "In Progress",
    "priority": "Medium",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Streetlights on major highway completely dead. Requires coordination with Street Lighting department.",
    "location": "Jaipur, Rajasthan",
    "city": "Jaipur",
    "district": "Jaipur",
    "state": "Rajasthan",
    "assignedAdminId": "A007",
    "assignedAdminName": "Rohan Mehta",
    "createdAt": "2026-07-31T12:00:00.000Z",
    "updatedAt": "2026-07-31T12:00:00.000Z",
    "dueAt": "2026-08-19T14:44:49.699Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-34-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Kabir Khan",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-31T12:00:00.000Z"
      },
      {
        "id": "ACT-34-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Rohan Mehta",
        "timestamp": "2026-07-31T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10035",
    "title": "Public bus route 414 suspended without notice",
    "citizen": "Sneha Iyer",
    "dept": "Public Transport",
    "departmentId": "D106",
    "date": "08 Aug 2026",
    "status": "Pending",
    "priority": "Medium",
    "sla": "Overdue",
    "slaColor": "red",
    "aiSummary": "Citizen reported: Public bus route 414 suspended without notice. Requires coordination with Public Transport department.",
    "location": "Ahmedabad, Gujarat",
    "city": "Ahmedabad",
    "district": "Ahmedabad",
    "state": "Gujarat",
    "assignedAdminId": "A006",
    "assignedAdminName": "Neha Patel",
    "createdAt": "2026-08-08T12:00:00.000Z",
    "updatedAt": "2026-08-08T12:00:00.000Z",
    "dueAt": "2026-08-14T04:59:07.190Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-35-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Sneha Iyer",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-08T12:00:00.000Z"
      },
      {
        "id": "ACT-35-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Neha Patel",
        "timestamp": "2026-08-08T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10036",
    "title": "Open manhole on pedestrian walkway",
    "citizen": "Vikram Joshi",
    "dept": "Drainage",
    "departmentId": "D107",
    "date": "10 Aug 2026",
    "status": "Resolved",
    "priority": "Medium",
    "sla": "Resolved",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Open manhole on pedestrian walkway. Requires coordination with Drainage department.",
    "location": "Bhubaneswar, Odisha",
    "city": "Bhubaneswar",
    "district": "Bhubaneswar",
    "state": "Odisha",
    "assignedAdminId": "A008",
    "assignedAdminName": "Ananya Das",
    "createdAt": "2026-08-10T12:00:00.000Z",
    "updatedAt": "2026-08-14T18:38:16.095Z",
    "dueAt": "2026-08-17T12:00:00.000Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-36-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Vikram Joshi",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-10T12:00:00.000Z"
      },
      {
        "id": "ACT-36-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Ananya Das",
        "timestamp": "2026-08-10T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10037",
    "title": "Public park equipment broken and rusted",
    "citizen": "Pooja Reddy",
    "dept": "Public Works",
    "departmentId": "D108",
    "date": "02 Aug 2026",
    "status": "Pending",
    "priority": "Medium",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Public park equipment broken and rusted. Requires coordination with Public Works department.",
    "location": "Hyderabad, Telangana",
    "city": "Hyderabad",
    "district": "Hyderabad",
    "state": "Telangana",
    "assignedAdminId": "A009",
    "assignedAdminName": "Vikram Rao",
    "createdAt": "2026-08-02T12:00:00.000Z",
    "updatedAt": "2026-08-02T12:00:00.000Z",
    "dueAt": "2026-08-17T18:13:03.299Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-37-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Pooja Reddy",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-02T12:00:00.000Z"
      },
      {
        "id": "ACT-37-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Vikram Rao",
        "timestamp": "2026-08-02T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10038",
    "title": "Tree branches entangling with overhead power lines",
    "citizen": "Rohan Gupta",
    "dept": "Electricity",
    "departmentId": "D109",
    "date": "11 Aug 2026",
    "status": "In Progress",
    "priority": "Medium",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Tree branches entangling with overhead power lines. Requires coordination with Electricity department.",
    "location": "New Delhi, Delhi",
    "city": "New Delhi",
    "district": "New Delhi",
    "state": "Delhi",
    "assignedAdminId": "A002",
    "assignedAdminName": "Priya Sharma",
    "createdAt": "2026-08-11T12:00:00.000Z",
    "updatedAt": "2026-08-11T12:00:00.000Z",
    "dueAt": "2026-08-15T18:01:36.635Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-38-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Rohan Gupta",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-11T12:00:00.000Z"
      },
      {
        "id": "ACT-38-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Priya Sharma",
        "timestamp": "2026-08-11T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10039",
    "title": "Irregular garbage collection schedule",
    "citizen": "Neha Menon",
    "dept": "Waste Management",
    "departmentId": "D110",
    "date": "29 Jul 2026",
    "status": "Resolved",
    "priority": "Medium",
    "sla": "Resolved",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Irregular garbage collection schedule. Requires coordination with Waste Management department.",
    "location": "Lucknow, Uttar Pradesh",
    "city": "Lucknow",
    "district": "Lucknow",
    "state": "Uttar Pradesh",
    "assignedAdminId": "A015",
    "assignedAdminName": "Karan Singh",
    "createdAt": "2026-07-29T12:00:00.000Z",
    "updatedAt": "2026-08-15T08:22:20.483Z",
    "dueAt": "2026-08-05T12:00:00.000Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-39-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Neha Menon",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-29T12:00:00.000Z"
      },
      {
        "id": "ACT-39-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Karan Singh",
        "timestamp": "2026-07-29T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10040",
    "title": "Low water pressure during morning hours",
    "citizen": "Aarav Sharma",
    "dept": "Water Supply",
    "departmentId": "D101",
    "date": "10 Aug 2026",
    "status": "In Progress",
    "priority": "Medium",
    "sla": "Overdue",
    "slaColor": "red",
    "aiSummary": "Citizen reported: Low water pressure during morning hours. Requires coordination with Water Supply department.",
    "location": "Mumbai, Maharashtra",
    "city": "Mumbai",
    "district": "Mumbai",
    "state": "Maharashtra",
    "assignedAdminId": "A001",
    "assignedAdminName": "Rajesh Kumar",
    "createdAt": "2026-08-10T12:00:00.000Z",
    "updatedAt": "2026-08-10T12:00:00.000Z",
    "dueAt": "2026-08-13T16:05:26.262Z",
    "escalated": false,
    "reopened": true,
    "reopenedAt": "2026-08-15T03:41:50.143Z",
    "reopenedBy": "Citizen",
    "reopenReason": "The issue was marked resolved but the problem persists.",
    "messages": [],
    "activities": [
      {
        "id": "ACT-40-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Aarav Sharma",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-10T12:00:00.000Z"
      },
      {
        "id": "ACT-40-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Rajesh Kumar",
        "timestamp": "2026-08-10T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10041",
    "title": "Faded zebra crossing markings",
    "citizen": "Ananya Singh",
    "dept": "Roads & Infrastructure",
    "departmentId": "D102",
    "date": "17 Jul 2026",
    "status": "Pending",
    "priority": "Low",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Faded zebra crossing markings. Requires coordination with Roads & Infrastructure department.",
    "location": "Bhopal, Madhya Pradesh",
    "city": "Bhopal",
    "district": "Bhopal",
    "state": "Madhya Pradesh",
    "assignedAdminId": "A013",
    "assignedAdminName": "Sanjay Joshi",
    "createdAt": "2026-07-17T12:00:00.000Z",
    "updatedAt": "2026-07-17T12:00:00.000Z",
    "dueAt": "2026-08-19T15:15:34.804Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-41-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Ananya Singh",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-17T12:00:00.000Z"
      },
      {
        "id": "ACT-41-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Sanjay Joshi",
        "timestamp": "2026-07-17T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10042",
    "title": "Stray animal menace near market area",
    "citizen": "Rahul Verma",
    "dept": "Civic Services",
    "departmentId": "D103",
    "date": "07 Aug 2026",
    "status": "Resolved",
    "priority": "Low",
    "sla": "Resolved",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Stray animal menace near market area. Requires coordination with Civic Services department.",
    "location": "Chennai, Tamil Nadu",
    "city": "Chennai",
    "district": "Chennai",
    "state": "Tamil Nadu",
    "assignedAdminId": "A010",
    "assignedAdminName": "Kavya Iyer",
    "createdAt": "2026-08-07T12:00:00.000Z",
    "updatedAt": "2026-08-15T10:47:33.375Z",
    "dueAt": "2026-08-21T12:00:00.000Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-42-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Rahul Verma",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-07T12:00:00.000Z"
      },
      {
        "id": "ACT-42-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Kavya Iyer",
        "timestamp": "2026-08-07T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10043",
    "title": "Mosquito breeding in stagnant park water",
    "citizen": "Priya Das",
    "dept": "Sanitation",
    "departmentId": "D104",
    "date": "07 Aug 2026",
    "status": "Pending",
    "priority": "Low",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Mosquito breeding in stagnant park water. Requires coordination with Sanitation department.",
    "location": "Pune, Maharashtra",
    "city": "Pune",
    "district": "Pune",
    "state": "Maharashtra",
    "assignedAdminId": "A014",
    "assignedAdminName": "Aditi Jain",
    "createdAt": "2026-08-07T12:00:00.000Z",
    "updatedAt": "2026-08-07T12:00:00.000Z",
    "dueAt": "2026-08-20T00:08:57.932Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-43-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Priya Das",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-07T12:00:00.000Z"
      },
      {
        "id": "ACT-43-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Aditi Jain",
        "timestamp": "2026-08-07T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10044",
    "title": "Bus shelter roof leaking during rain",
    "citizen": "Kabir Khan",
    "dept": "Public Transport",
    "departmentId": "D105",
    "date": "23 Jul 2026",
    "status": "In Progress",
    "priority": "Low",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Bus shelter roof leaking during rain. Requires coordination with Public Transport department.",
    "location": "Ahmedabad, Gujarat",
    "city": "Ahmedabad",
    "district": "Ahmedabad",
    "state": "Gujarat",
    "assignedAdminId": "A006",
    "assignedAdminName": "Neha Patel",
    "createdAt": "2026-07-23T12:00:00.000Z",
    "updatedAt": "2026-07-23T12:00:00.000Z",
    "dueAt": "2026-08-15T18:38:55.653Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-44-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Kabir Khan",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-23T12:00:00.000Z"
      },
      {
        "id": "ACT-44-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Neha Patel",
        "timestamp": "2026-07-23T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10045",
    "title": "Request for additional street dustbins",
    "citizen": "Sneha Iyer",
    "dept": "Waste Management",
    "departmentId": "D106",
    "date": "17 Jul 2026",
    "status": "Resolved",
    "priority": "Low",
    "sla": "Resolved",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Request for additional street dustbins. Requires coordination with Waste Management department.",
    "location": "Lucknow, Uttar Pradesh",
    "city": "Lucknow",
    "district": "Lucknow",
    "state": "Uttar Pradesh",
    "assignedAdminId": "A015",
    "assignedAdminName": "Karan Singh",
    "createdAt": "2026-07-17T12:00:00.000Z",
    "updatedAt": "2026-08-15T06:21:47.121Z",
    "dueAt": "2026-07-31T12:00:00.000Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-45-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Sneha Iyer",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-17T12:00:00.000Z"
      },
      {
        "id": "ACT-45-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Karan Singh",
        "timestamp": "2026-07-17T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10046",
    "title": "Streetlight flickering occasionally",
    "citizen": "Vikram Joshi",
    "dept": "Street Lighting",
    "departmentId": "D107",
    "date": "11 Aug 2026",
    "status": "In Progress",
    "priority": "Low",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Streetlight flickering occasionally. Requires coordination with Street Lighting department.",
    "location": "Jaipur, Rajasthan",
    "city": "Jaipur",
    "district": "Jaipur",
    "state": "Rajasthan",
    "assignedAdminId": "A007",
    "assignedAdminName": "Rohan Mehta",
    "createdAt": "2026-08-11T12:00:00.000Z",
    "updatedAt": "2026-08-11T12:00:00.000Z",
    "dueAt": "2026-08-17T11:53:22.859Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-46-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Vikram Joshi",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-11T12:00:00.000Z"
      },
      {
        "id": "ACT-46-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Rohan Mehta",
        "timestamp": "2026-08-11T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10047",
    "title": "Minor crack on pavement",
    "citizen": "Pooja Reddy",
    "dept": "Roads & Infrastructure",
    "departmentId": "D108",
    "date": "19 Jul 2026",
    "status": "Pending",
    "priority": "Low",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Minor crack on pavement. Requires coordination with Roads & Infrastructure department.",
    "location": "Bhopal, Madhya Pradesh",
    "city": "Bhopal",
    "district": "Bhopal",
    "state": "Madhya Pradesh",
    "assignedAdminId": "A013",
    "assignedAdminName": "Sanjay Joshi",
    "createdAt": "2026-07-19T12:00:00.000Z",
    "updatedAt": "2026-07-19T12:00:00.000Z",
    "dueAt": "2026-08-19T09:45:04.643Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-47-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Pooja Reddy",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-19T12:00:00.000Z"
      },
      {
        "id": "ACT-47-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Sanjay Joshi",
        "timestamp": "2026-07-19T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10048",
    "title": "Delay in processing property tax receipt",
    "citizen": "Rohan Gupta",
    "dept": "Civic Services",
    "departmentId": "D109",
    "date": "29 Jul 2026",
    "status": "Resolved",
    "priority": "Low",
    "sla": "Resolved",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Delay in processing property tax receipt. Requires coordination with Civic Services department.",
    "location": "Chennai, Tamil Nadu",
    "city": "Chennai",
    "district": "Chennai",
    "state": "Tamil Nadu",
    "assignedAdminId": "A010",
    "assignedAdminName": "Kavya Iyer",
    "createdAt": "2026-07-29T12:00:00.000Z",
    "updatedAt": "2026-08-15T00:26:18.125Z",
    "dueAt": "2026-08-12T12:00:00.000Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-48-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Rohan Gupta",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-29T12:00:00.000Z"
      },
      {
        "id": "ACT-48-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Kavya Iyer",
        "timestamp": "2026-07-29T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10049",
    "title": "Park bench requires repainting",
    "citizen": "Neha Menon",
    "dept": "Public Works",
    "departmentId": "D110",
    "date": "30 Jul 2026",
    "status": "Pending",
    "priority": "Low",
    "sla": "On Time",
    "slaColor": "green",
    "aiSummary": "Citizen reported: Park bench requires repainting. Requires coordination with Public Works department.",
    "location": "Hyderabad, Telangana",
    "city": "Hyderabad",
    "district": "Hyderabad",
    "state": "Telangana",
    "assignedAdminId": "A009",
    "assignedAdminName": "Vikram Rao",
    "createdAt": "2026-07-30T12:00:00.000Z",
    "updatedAt": "2026-07-30T12:00:00.000Z",
    "dueAt": "2026-08-16T16:58:43.055Z",
    "escalated": false,
    "reopened": false,
    "messages": [],
    "activities": [
      {
        "id": "ACT-49-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Neha Menon",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-07-30T12:00:00.000Z"
      },
      {
        "id": "ACT-49-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Vikram Rao",
        "timestamp": "2026-07-30T12:05:00.000Z"
      }
    ]
  },
  {
    "id": "GRV-10050",
    "title": "Major water pipeline burst flooding street",
    "citizen": "Aarav Sharma",
    "dept": "Water Supply",
    "departmentId": "D101",
    "date": "14 Aug 2026",
    "status": "In Progress",
    "priority": "Low",
    "sla": "Overdue",
    "slaColor": "red",
    "aiSummary": "Citizen reported: Major water pipeline burst flooding street. Requires coordination with Water Supply department.",
    "location": "Mumbai, Maharashtra",
    "city": "Mumbai",
    "district": "Mumbai",
    "state": "Maharashtra",
    "assignedAdminId": "A001",
    "assignedAdminName": "Rajesh Kumar",
    "createdAt": "2026-08-14T12:00:00.000Z",
    "updatedAt": "2026-08-14T12:00:00.000Z",
    "dueAt": "2026-08-14T02:25:05.990Z",
    "escalated": false,
    "reopened": true,
    "reopenedAt": "2026-08-14T19:36:06.383Z",
    "reopenedBy": "Citizen",
    "reopenReason": "The issue was marked resolved but the problem persists.",
    "messages": [],
    "activities": [
      {
        "id": "ACT-50-1",
        "type": "submitted",
        "actor": "Citizen",
        "actorName": "Aarav Sharma",
        "description": "Grievance filed by citizen.",
        "timestamp": "2026-08-14T12:00:00.000Z"
      },
      {
        "id": "ACT-50-2",
        "type": "assigned",
        "actor": "System",
        "actorName": "System",
        "description": "Assigned to Rajesh Kumar",
        "timestamp": "2026-08-14T12:05:00.000Z"
      }
    ]
  }
];
